### ISSUE TITLE
can not build successfully

### ISSUE THREAD

**Issue by yexb69** [DynamoDS/Dynamo-Advance-Steel#16]
When I build "Dynamo Extension for Advance Steel" on my computer,  there is an error.

C:\GitHub\Dynamo-Advance-Steel\src\DynamoAdvanceSteel\CommandClass.cs(175,64,175,87): error CS0117: 'Utilities' does not contain a definition for 'GetGeometryFactoryPath2'

Can you help me solve the problem?
Thanks a lot!

**Comment by QilongTang** [comment]
@yexb69 Hi, although not author of this repo but after loading the project in Visual Studiom this DynamoShapeManager is referenced from C:\Program Files\Dynamo\Dynamo Core\2\DynamoShapeManager.dll which is an installed location of Dynamo 2.X. In your case, I suspect that you do not have Dynamo 2.X installed and have a legacy version, that should be the reason why your project build but reference does not contain such function. You can try installing Dynamo 2.0 from dynamobuilds.com to resolve this. Let us know if you still have such problem after installing. 

Cheers

**Comment by vpavel04** [comment]
@yexb69 please install dynamo 2.0.2, latest version. It should work. That function is not available in 2.0.1 or 2.0.0

**Comment by yexb69** [comment]
Hi, sir
Thanks a lot for your advice, the problem is solved.
yexb69

On Nov 19, 2018, at 1:53 AM, vpavel04 <notifications@github.com<mailto:notifications@github.com>> wrote:


@yexb69<https://github.com/yexb69> please install dynamo 2.0.2, latest version. It should work. That function is not available in 2.0.1 or 2.0.0
