### ISSUE TITLE
Autodesk.LibG.LibGPINVOKE - problem

### ISSUE THREAD

**Issue by roduq** [DynamoDS/Dynamo-Advance-Steel#17]
![image](https://user-images.githubusercontent.com/45419153/50839599-f03f9e00-1360-11e9-8eac-9a4d9a1a0f86.png)

It says that Point.ByCoordinates operation has failed. What do I need to do to make it work properly? or maybe what i did not do :)

**Comment by vpavel04** [comment]
what version of AutoCAD are you using?

**Comment by roduq** [comment]
AC 2019 and Dynamo 2.02

**Comment by vpavel04** [comment]
do you have the latest 2.02, from 3rd December? http://dynamobuilds.com/

**Comment by roduq** [comment]
Thank you, it was that. I thought i was working on Dynamo 2.02 but in reality it opened a ealier version.
