### ISSUE TITLE
Installing problem

### ISSUE THREAD

**Issue by flecheria** [DynamoDS/Dynamo-Advance-Steel#8]
HI,
I follow the instruction, but I stil have some problems with installation. No icons on the RibbonBar of AutoCad/AdvanceSteel.
- I've got DynamoExtension installed here C:\Program Files\Dynamo\Dynamo Advance Steel\2018
- I created an Addons folder inside C:\Program Files\Autodesk\AutoCAD 2018\ADVS\Addons

I've some problems to find the folder for the binary of ADVS because I can't found this on my machine
HKEY_LOCAL_MACHINE\Software\Autodesk\AdvanceSteel\2017\Environment\BinPath

Normally which is the binary path for ADVS?

At the end, this is my MyAddons.xml
```
<?xml version="1.0" encoding="utf-8"?>
<AddonsData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Addons>
    <Addon>
      <Name>DynamoAdvanceSteel</Name>
      <FullPath>C:\Program Files\Dynamo\Dynamo Advance Steel\2018\DynamoAdvanceSteel.dll</FullPath>
    </Addon>
  </Addons>
</AddonsData>
```
What am I missing?
Thanks
Paolo

**Comment by bogdanorzea** [comment]
Hi @flecheria,
Have you tried typing RUNDYNAMO on the Command Line in AdvanceSteel to start the Dynamo Extension? 
Also, I strongly recommend applying Advance Steel 2018 HF1 as this update might solve the missing icon.

**Comment by flecheria** [comment]
Thanks for the answer. Yes it's all working. First I loaded DynamoAdvanceSteel.dll with NETLOAD, but really it doesn't need this. With RUNDYNAMO all works like a charm.

Still remain the problem about the lack of Dynamo's icon inside the Addins tab.

I check the AdvanceSteel SDK 2018 docs and they changed the way to registry the addin, now:
- you need to add a new setting key in C:\Program Files\Autodesk\AutoCAD 2018\ADVS\ASSettings_Advance.xml
- create  [HKEY_LOCAL_MACHINE\SOFTWARE\Autodesk\AdvanceSteel\<Advance_Steel_ Version_Number> \NETAddins\<Addin_Name>] with the following path C:\Program Files\Dynamo\Dynamo Advance Steel\2018\DynamoAdvanceSteel.dll

But still no icon. Anyway indication about AS2017 are no more valid.
P

**Comment by bogdanorzea** [comment]
There were some changes from AS 2017 to AS 2018. Please check the corresponding branches for different addin versions. 
Please update to Advance Steel 2018 HF1 to solve the missing icon.

Bogdan.

**Comment by flecheria** [comment]
Now it works, icon too using instruction from ADVS SDK2018 + Advance Steel 2018 HF1 update
